# Generated by Django 3.2.12 on 2022-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alertconfig_alertsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfig',
            name='community',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Discord', 'Discord')], max_length=30),
        ),
    ]
