# Generated by Django 3.2.12 on 2022-04-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_alertconfig_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsystem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert', to=settings.AUTH_USER_MODEL),
        ),
    ]
