# Generated by Django 3.2.12 on 2022-04-03 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("website_link", models.URLField(max_length=2000)),
                ("twitter_link", models.URLField(max_length=500)),
                ("discord_link", models.URLField(max_length=500)),
                ("opensea_link", models.URLField(max_length=500)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
    ]
