# Generated by Django 3.2.12 on 2022-04-03 09:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ranking",
            fields=[
                ("twitter_project_id", models.CharField(max_length=100)),
                ("twitter_followers_count", models.CharField(max_length=200)),
                (
                    "twitter_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "twitter_engagement_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("discord_followers_count", models.CharField(max_length=200)),
                (
                    "discord_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranking.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
