# Generated by Django 3.2.12 on 2022-04-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0003_twitterfollowersrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordFollowersRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followers_count", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "ranking_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranking.ranking",
                    ),
                ),
            ],
        ),
    ]
