# Generated by Django 3.2.12 on 2022-04-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0004_discordfollowersrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ranking",
            old_name="twitter_project_id",
            new_name="twitter_user_id",
        ),
    ]
