# Generated by Django 3.2.12 on 2022-04-10 16:57

from django.db import migrations, models
import tracknfts.ranking.models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20220408_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=tracknfts.ranking.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='discord_link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='opensea_link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter_link',
            field=models.URLField(max_length=2000),
        ),
    ]
