# Generated by Django 3.2.12 on 2022-04-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_remove_watchlist_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_watchlist', to='ranking.project'),
        ),
    ]
