# Generated by Django 3.2.12 on 2022-04-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_alter_ranking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={},
        ),
    ]
